# syntax=docker/dockerfile:1
FROM cypress/included:16.0.0@sha256:2ad59498de089a8eb03b6a3923c4e2f0801099f9be044ae2825531cb585e9370
ENV CYPRESS_INSTALL_BINARY=0
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY frontend/static/ ./static/
COPY frontend/tests/ ./tests/
COPY frontend/cypress.config.js ./
COPY frontend/cypress/ ./cypress/
ENTRYPOINT []
CMD ["npm", "run", "test:unit:ci"]
